# .github/workflows/build-and-test.yml

name: Build and Test Go Application

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches-ignore:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'  # Ajusta la versión de Go si es necesario

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run lint
        run: go vet ./...
