# .github/workflows/build-and-test.yml

name: Build and Test

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches-ignore:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia a la versión de Node.js que uses

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
